#!/bin/bash 
set -e

# skip test_development_guidelines_matches_ci because
# we're installed, so the path doesn't match development
SKIP_TESTS=test_development_guidelines_matches_ci
# failed to raise a warning.
SKIP_TESTS="$SKIP_TESTS or test_RandomState_only_funcs"
# See https://github.com/dask/dask/issues/10418
SKIP_TESTS="$SKIP_TESTS or test_division_or_partition"

cp conftest.py "$AUTOPKGTEST_TMP"
for py in $(py3versions --supported)
do
  cd "$AUTOPKGTEST_TMP"
  echo "Testing with $py:"
  http_proxy= $py -m pytest -k "not ( ${SKIP_TESTS} )" -m "not network" -v --pyargs dask
done
